name: Build
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v2
        - name: Publish
          uses: cloudflare/wrangler-action@1.3.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            preCommands: |
              echo 'import process from"process";let a="";process.stdin.on("readable",()=>{const b=process.stdin.read();a+=null==b?"":b}),process.stdin.on("end",()=>{process.stdout.write(JSON.stringify(JSON.parse(a).filter(b=>b.title.includes("KV_BOT_STORAGE"))[0].id))});' > script.mjs
              export KV_NAMESPACE_ID=$(wrangler kv:namespace list | node script.mjs)
              echo "kv_namespaces = [{binding=\"KV_BOT_STORAGE\", id=04f4d94e56af46568f3c8318aba04c3e}]" >> wrangler.toml
              [ -z "$SECRET_TELEGRAM_API_TOKEN" ] && echo "Secret SECRET_TELEGRAM_API_TOKEN not set, creating dummy one..." && SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret" || true
            secrets: |
              SECRET_TELEGRAM_API_TOKEN
          env:
            SECRET_TELEGRAM_API_TOKEN: 2122673619:AAGxTWX4FmtmDaf38W1xQrbGYt5V8G8X5ys
